# Generated by Django 4.2.5 on 2023-10-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisuals_stock', '0003_material_extraccionmaterial_devolucionmaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_extraida', models.PositiveIntegerField()),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiovisuals_stock.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
