# Generated by Django 4.2.5 on 2023-10-10 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisuals_stock', '0006_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userprofile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='audiovisuals_stock.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
