# Generated by Django 4.2.5 on 2023-10-11 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisuals_stock', '0007_customuser_userprofile_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraccionmaterial',
            name='cantidad_extraida',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
